[config.wallpaper]
command = "swww"
arguments = ["img", "-t", "wave", "--transition-duration=3"]
set = true

[templates.zenChrome]
input_path = '~/.local/share/matugen/templates/zenChrome.css'
output_path = '~/.cache/zenChrome.css'
post_hook = 'ln -f ~/.cache/zenChrome.css ~/.var/app/app.zen_browser.zen/.zen/*release*/chrome/userChrome.css'

[templates.zenContent]
input_path = '~/.local/share/matugen/templates/zenContent.css'
output_path = '~/.cache/zenContent.css'
post_hook = 'ln -f ~/.cache/zenChrome.css ~/.var/app/app.zen_browser.zen/.zen/*release*/chrome/userContent.css'

[templates.foot]
input_path = '~/.local/share/matugen/templates/foot.ini'
output_path = '~/.config/foot/colors.ini'

[templates.nvim]
input_path = '~/.local/share/matugen/templates/nvim.lua'
output_path = '~/.config/nvim/lua/config/colorscheme.lua'

[templates.terminal]
input_path = '~/.local/share/matugen/templates/term_colors.txt'
output_path = '/tmp/term_colors.txt'
post_hook = '~/.local/share/scripts/change_term_colors.sh'

[templates.starship]
input_path = '~/.local/share/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.vesktop]
input_path = '~/.local/share/matugen/templates/vesktop.css'
output_path = '~/.var/app/dev.vencord.Vesktop/config/vesktop/settings/quickCss.css'

[templates.hyprland]
input_path = '~/.local/share/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/vars.conf'

[templates.niri]
input_path = '~/.local/share/matugen/templates/niri.kdl'
output_path = '~/.config/niri/config.kdl'

[templates.mako]
input_path = '~/.local/share/matugen/templates/mako.conf'
output_path = '~/.config/mako/config'
post_hook = 'makoctl reload'

[templates.slurp]
input_path = '~/.local/share/matugen/templates/screenshot.sh'
output_path = '~/.local/share/scripts/screenshot.sh'

[templates.fuzzel]
input_path = '~/.local/share/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.eww]
input_path = '~/.local/share/matugen/templates/eww.scss'
output_path = '~/.config/eww/scss/colors.scss'

[templates.icons]
input_path = '~/.local/share/matugen/templates/icons.txt'
output_path = '/tmp/icons.txt'
post_hook = '~/.local/share/scripts/change_folder.sh `< /tmp/icons.txt` && rm /tmp/icons.txt'

[templates.gtk3]
input_path = '~/.local/share/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'systemctl --user restart xdg-desktop-portal-gtk.service'

[templates.gtk4]
input_path = '~/.local/share/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt5ct]
input_path = '~/.local/share/matugen/templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.local/share/matugen/templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.mpv_modernz]
input_path = '~/.local/share/matugen/templates/modernz.conf'
output_path = '~/.config/mpv/script-opts/modernz.conf'

[templates.mpv]
input_path = '~/.local/share/matugen/templates/mpv.conf'
output_path = '/tmp/mpv.conf'
post_hook = 'awk "NR==1 {printf \"background-color=%.2f/%.2f/%.2f\n\", (strtonum(\"0x\" substr(\$0,1,2)))/255, (strtonum(\"0x\" substr(\$0,3,2)))/255, (strtonum(\"0x\" substr(\$0,5,2)))/255; next} 1" /tmp/mpv.conf > ~/.config/mpv/mpv.conf && rm /tmp/mpv.conf'

[templates.imv]
input_path = '~/.local/share/matugen/templates/imv'
output_path = '~/.config/imv/config'

[templates.zathura]
input_path = '~/.local/share/matugen/templates/zathurarc'
output_path = '~/.config/zathura/zathurarc'

[templates.tty]
input_path = '~/.local/share/matugen/templates/cmdline.conf'
output_path = '/tmp/cmdline_colors.conf'
post_hook = '{ sudo colorize-cmdline.sh && notify-send "Cmdline Updated" ":3" } &'
