require("config.cmp")
require("config.file_manager")
require("config.fzf")
require("config.git")
require("config.look")
require("config.lsp")
require("config.opts")
require("config.terminal")
require("config.treesitter")

require("config.colorscheme")
require("config.keybinds")

require("config.strudel")
require("config.typst")
